Develop feature
AlejandroNo4/re-former pull request #1
Opened 2021-03-08 20:38 UTC by AlejandroNo4

This project was made for learning proposes, to practice the way of creating forms with Rails. It was for practice and understand the way data is structured and sent to the controller.

2021-03-08 23:48 UTC, LamiaSristy requested changes
# Status: Change Required. ♻️

Hello @AlejandroNo4. 
**I can assume a lot of effort and dedication needs for coding, and all are here present in your project.**

## The highlights: 
* The `linters` set up correctly.
*  The create and edit user actions are working fine.
*  Great job with error messages for fail validations.

## What to do next: 

**Please make sure all the required point added to get approval**

**[REQUIRED]** 👇 

- [ ] In the `README` file, kindly add instructions for cloning and running the project locally, ex: run `bundle install &&  yarn  && rails db:migrate && rails s`. This will help the user to easily clone your project.

- [ ] Kindly give your PR a meaningful title with a proper description of the project and a little more descriptive commit messages, so that your PR is professional.

- [x]  In the `UsersController`, `update` action, kindly change the ` redirect_to @user` to  `redirect_to edit_user_path`, as currently you created only :new, :create, :edit, :update actions. So you need to redirect to  `edit_user_path` if user is updated.

- [x] In the views, kindly use the tag `form_with`, as it is given as instructions in the [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms) project.  See my attached image also 👇 
![odin](https://user-images.githubusercontent.com/56501603/110396073-9edde700-806f-11eb-8086-667b9c37ac20.png)
##

**Your feature branch's name is not appropriate, consider not using the word develop in the naming of feature-branch, this will be ensuring your repository is more professional**

Please make the changes and ask for a re-review.


Feel free to reach me on slack @lamiasristy 🙋

Keep up the spirit always. Happy Coding 💻

2021-03-08 23:50 UTC, LamiaSristy commented on app/controllers/users_controller.rb
> +    end
Change the redirection after updating the user, `redirect_to edit_user_path`

2021-03-08 23:52 UTC, LamiaSristy commented on app/views/users/edit.html.erb
> +  <%= f.submit %>
Use `#form_with` here as it was instructed in the [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms) project.

2021-03-08 23:52 UTC, LamiaSristy commented on app/views/users/new.html.erb
> +<% end %>
Use `#form_with` here as it was instructed in the [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms) project.

2021-03-09 01:13 UTC, AlejandroNo4 commented
I had problems in the past changing the name of the branch. I decided to leave the name as it is, Investigate more about how to do it, and avoid doing it in the future. 
Also, I will try to make better commits.

Thank you!

2021-03-09 01:34 UTC, mke2111 approved these changes
# **🎉 STATUS: APPROVED 🎉** 

## Hey @AlejandroNo4, 👋🏽 
 **Congratulations 🥳 🥂 . Your app meets the minimum requirements for approval.**

- [x] I'm approving this project since you had initially used the `form_for` in the edit.html.erb.
- [ ] [OPTIONAL] In the readme file. Add all commands needed to get the app ready before starting the server. Such as `bundle install` and `rails db:migrate`.

**You may now merge to the develop branch and submit a project completion form. 👍🏽** 

## Cheers!! 🍹 

## Reach me on slack for a chitchat 🆘  **Roy Mukuye**

2021-03-09 20:07 UTC, merged